id: P000368
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG4449
  title: བཅོམ་ལྡན་འདས་དཔལ་དགྱེས་པ་རྡོ་རྗེའི་ཆོ་ག་ནག་པོ་འགྲོ་ཤེས་སུ་བཀོད་པ
  author: ''
  volumes:
    dec805f8fb144fb7bf5673f46ddfd11b:
      image_group_id: I1KG4537
      title: Volume 1 of bcom ldan 'das dpal dgyes pa rdo rje'i cho ga nag po 'gro
        shes su bkod pa
      volume_number: 1
      total_pages: 636
      base_file: v001.txt
